version: '3.8'
services:
  refreshBase:
    image: redis:6.2-alpine
    restart: always
    env_file:
      - .env
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - refreshBase:/data
volumes:
  refreshBase:
    driver: local